### ISSUE TITLE
How do I set it up

### ISSUE THREAD

**Issue by talwarvidul** [anush-cr/mockstock#1]
Hello, I have downloaded the zip file. We're having a mockstocks event in our college.

However, I cannot find a sql file, neither can I find the instructions on how to set up the application. Even if I have to make a database, I don't know the specifications. The TODO list continuously shows 'All Done', that too online only. I have no idea how to set up this application. The readme.md file contains the description of the application, not the instructions to set it up.

Also, I'm getting a 500 internal server error when I open the Admin setup page.

Please help.

**Comment by anush-cr** [comment]
Hi,
The db_config.txt file points to a live database. Which is why TODO always shows all done. Replace with your own credentials --> format as far as i remember is hostname->username->password->database_name.

Also the 500 error maybe related to how your web server is configured to parse .htpasswd files. You have to set it up to parse .ht* files.
